version: "3.8"
services:
  django:
    container_name: django
    build: ./
    ports:
      - "8000:8000"
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: nginx_Dockerfile
    ports:
      - "80:80"
    depends_on:
      - django
