# Generated by Django 4.2 on 2023-08-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poster",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="poster",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
